### ISSUE TITLE
set Org for a session

### ISSUE THREAD

**Issue by ohbikepilot** [mbegan/Duo-PSModule#11]
I am looking for a way to set $duoDefaultOrg or some similar variable to one of the Orgs configured in Duo_org.ps1. The module properly sets the default org, however it would be nice to be able to change the org on the fly without having to use -dOrg with every commandlet. 

An example of this usage might be...
-Dev and Prod are configured in Duo_org.ps1
- Dev is set as default
- I want to set Prod to the default org for some time without editing Duo_org or using -dOrg for every command. 

Thanks in advance for your help. I'm not sure if this is something I'm overlooking or a new feature.

**Comment by mbegan** [comment]
Hi @ohbikepilot 
First, thanks for the PR, i'll take a look at that when i have a little more time.  Looks like a good addition.

re: default org and toggling back and fourth.

I tend to not use it as much and i'll generally right scripts and set an alternate variable that i use to explicitly set the -dOrg param for each command.

That said you should be able to overwrite the variable within a powershell session at any time.

if your duo_org file has $DuoDefaultOrg="dev" and you are running in the same powershell session you should be able to just change the variable like normal $DuoDefaultOrg="prod"

See below (a different module for a superior product ;-) but the example should translate)

```powershell
PS> $oktaDefOrg                                                                                                                            
matt
PS> $user = oktaGetUserbyID -userName matt.egan                                                                            
PS> $user.id
00uabxx4hlwm47RSV0h7                                                                                                                                             
PS> $oktaDefOrg='okp1'
PS> $user = oktaGetUserbyID -userName matt.egan
PS> $user.id
00u1a7qfdw3KgTkZE1d8
```

**Comment by ohbikepilot** [comment]
huh... I swear that I tried setting $DuoDefaultOrg and that it didn't work.

As I'm trying it now $DuoDefaultOrg and $DuoOrgs aren't available
variables, yet I can run commands on my default site (Dev).
If I set $DuoDefaultOrg = "Prod" then run duoGetUser -username it still
runs on "Dev". If I specify -dOrg $DuoDefaultOrg it runs on prod.

Anyway, thanks for the help. The module is fantastic even if I cant switch
sites.

**Comment by mbegan** [comment]
Odd, that really should work.

the variables wouldn't/shouldn't be available until after you import the import the module and if you try to define them prior to importing the module they'd likely be clobbered but after importing the module you should be able to change it at will.

i wonder if the powershell version changes this behavior, note i'm running powershell 6 on a mac.

```powershell
PS > $PSVersionTable                                                                                                                        
Name                           Value                                                                                                                            
----                           -----                                                                                                                            
PSVersion                      6.0.0-rc.2                                                                                                                       
PSEdition                      Core                                                                                                                             
GitCommitId                    v6.0.0-rc.2                                                                                                                      
OS                             Darwin 17.3.0 Darwin Kernel Version 17.3.0: Thu Nov  9 18:09:22 PST 2017; root:xnu-4570.31.3~1/RELEASE_X86_64                    
Platform                       Unix                                                                                                                             
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                                                          
PSRemotingProtocolVersion      2.3                                                                                                                              
SerializationVersion           1.1.0.1                                                                                                                          
WSManStackVersion              3.0                                                                                                                              

PS > Get-Variable -Name oktaDefOrg | fl                                                                                                     
PSPath        : Microsoft.PowerShell.Core\Variable::oktaDefOrg
PSDrive       : Variable
PSProvider    : Microsoft.PowerShell.Core\Variable
PSIsContainer : False
Name          : oktaDefOrg
Description   : 
Value         : okp1
Visibility    : Public
Module        : 
ModuleName    : 
Options       : None
Attributes    : {System.Management.Automation.ArgumentTypeConverterAttribute}
```
