### ISSUE TITLE
Module license?

### ISSUE THREAD

**Issue by sintaxasn** [mbegan/Duo-PSModule#13]
Hi there,

Do you have a a license agreement for this project? And also for your Okta module project? I'd like to be able to use myself, however my company has pretty strict guidelines on open-source software and requiring some sort of license, like Apache 2.0 (which I see you've used elsewhere).

Thanks in advance!

Dan

**Comment by mbegan** [comment]
Oversight on my part, addressed with #aebd3da

Thanks for bringing it to my attention

Also an obligatory plug, if you want superior MFA and more checkout Okta ;-)
