### ISSUE TITLE
Creating a new phone with predelay and postdelay

### ISSUE THREAD

**Issue by DustinEJD** [mbegan/Duo-PSModule#16]
Hi There,

I was just wondering how to use the provided wrapper to create a new phone and add a predelay as well as a postdelay to it, then associate it to a user. I apologize in advance as I understand this is probably an easy command, which I cannot seem to be able to figure out.

Thank you in advance,
Dustin

**Comment by mbegan** [comment]
So there are three commands you'll use (assuming the user already exists)

All of this assumes you have the module [installed and setup](https://github.com/mbegan/Duo-PSModule#getting-started)

commands
- duoCreatePhone
   - https://duo.com/docs/adminapi#create-phone
- duoGetUser
   - https://duo.com/docs/adminapi#retrieve-users
- duoAssocUserToPhone
   - https://duo.com/docs/adminapi#associate-phone-with-user

```powershell
#create a new phone with extension, predelay and postdelay
$newPhone = duoCreatePhone -number +15551234567 -type landline -platform unknown -predelay 3 -postdelay 2 -extension 1234 -name "Office Phone"

#get a duo user object to associate this new phone with
$targetUser = duoGetUser -username myUser

#associate the user with the phone
duoAssocUserToPhone -user_id $targetUser.user_id -phone_id $newPhone.phone_id

```
