### ISSUE TITLE
Get more than 100 users

### ISSUE THREAD

**Issue by schindlj** [mbegan/Duo-PSModule#22]
It looks like right now the duoGetUser command currently only pulls the first 100 users if the user selection.  This is the default by the admin api.  

Could it be possible to change the command to get ALL users?  I may be missing something regarding the parameter,  if so I apologize.

**Comment by bustabust** [comment]
Duo is implementing pagination for their API calls:

https://help.duo.com/s/article/4744?language=en_US

**Comment by rjrbytes** [comment]
@schindlj I believe this is fixed by my submitted pull request from a week ago to support the pagination parameter (also fixes the Json size issue). I've been using the submitted code for a week on a production script (managing about 3000 enrolled users) without incident.

**Comment by mbegan** [comment]
Addressed with the merge of #21 

@schindlj, can you test and confirm?

**Comment by schindlj** [comment]
Apologies for the delay.  100% working with the new calls!  Thanks!
