### ISSUE TITLE
How can I pull individual properties out of the objects?

### ISSUE THREAD

**Issue by ar-kaizen** [mbegan/Duo-PSModule#32]
Can you provide an example of how to pull the phone_id out of the phones object from duoGetUset?

I'm trying to pull the phone_id property out so I can use it in duoSendSMS.

I've tried select-property and expandproperty methods and they either don't seem to work, or say that phone_id isn't a valid property.

I apologize if this is more Powershell 101 then an actual implementation of this module, which is serving an awesome purpose for automation I'm writing.

I've currently devised a way around it by setting phones to a string, splitting it into an array on ";", taking index 7 which is "phone_id=xxxxx", and then stripping "phone_id=" from the result to ultimately get the phone ID but that seems so janky!

If you can provide an example on how to extract phone_id into a string that would be awesome!

Thanks in advance!

**Comment by hasan1st** [comment]
Hierarchy is as below:

> User
> __ Phones
> ____ Phone_ID

If you want to get a phone ID for a user it would be something like this
`(duogetuser -username xyz).phones.phone_id`

However you should also keep in mind that a user is allowed to have multiple phones, so this may return multiple IDs.

**Comment by ar-kaizen** [comment]
Aah I see! I'm going to give that a try! That makes sense. I have thought about the multiple phones thing, and don't think that will be an issue for the automation I'm putting together for the specific business purpose.

Also, you're probably right. I didn't quite think about that and probably should have as the question could have probably been answered at a general level I'm sure.
