### ISSUE TITLE
Invalid signature in request credentials

### ISSUE THREAD

**Issue by ekinnee** [mbegan/Duo-PSModule#4]
Verified keys and such, gives invalid signature in request.

**Comment by dicconb** [comment]
Are you seeing this exact output:
40103 ; Invalid signature in request credentials

I can only produce that error by deliberately entering an incorrect value for sKey in my Duo_org.ps1 file.

Are you storing your secret key in Duo_org.ps1 as plaintext (sKey) or encrypted (sKeyEnc)? If you encrypt your secret key using the duoEncskey I believe the output will only be valid for the current Windows user (ie if you use encryption you can't share a Duo_org.ps1 file between multiple windows accounts).

**Comment by mbegan** [comment]
Hi ekinnee,  like dicconb i can only reproduce if I have a 'typo' in my config file (note the difference between the sKey and sKeyEnc directives in the config file)

That said i had issues with the timestamp generation that is used in the generation of the signature.  Can you provide any details about your client config($psverisontable output, timezone and language settings)  I could have something else going on.

-Matt

**Comment by ekinnee** [comment]
I'm still working through the fact that I am not the "owner" and am being passed the login info via email. I believe you are correct on the cause.






On Thu, Sep 1, 2016 at 9:54 AM -0500, "Matt Egan" <notifications@github.com> wrote:












Hi ekinnee,  like dicconb i can only reproduce if I have a 'typo' in my config file (note the difference between the sKey and sKeyEnc directives in the config file)



That said i had issues with the timestamp generation that is used in the generation of the signature.  Can you provide any details about your client config($psverisontable output, timezone and language settings)  I could have something else going on.



-Matt

**Comment by ekinnee** [comment]
After being given owner rights and retrieving the keys myself it all works.
Thanks!

On Sep 1, 2016, at 09:55, Erick Kinnee <erick@kinnee.net> wrote:

I'm still working through the fact that I am not the "owner" and am being
passed the login info via email. I believe you are correct on the cause.





On Thu, Sep 1, 2016 at 9:54 AM -0500, "Matt Egan" <notifications@github.com>
wrote:

Hi ekinnee, like dicconb i can only reproduce if I have a 'typo' in my

**Comment by mbegan** [comment]
Thanks for the feedback
