### ISSUE TITLE
Modify duo users

### ISSUE THREAD

**Issue by jfertig** [mbegan/Duo-PSModule#6]
Is it possible to modify existing users with the current version?   (email address or realname)   if not,   I should be able able to piece something together,   but I figured I would ask first. 

Thanks again for your work on this... It has been very helpful.

**Comment by mbegan** [comment]
Hi There, 

Yes the same function used to create a user (duoCreateUser) is used to modify a user.  The difference between creating a user and modifying a user is that you must provide the user_id to the call when performing an update.

``` powershell
duoCreateUser -user_id DUxxxxxxxxxxxxxxxxx0 -realname "New Name"
```

Hope that helps
-Matt

**Comment by jfertig** [comment]
I'll give that a run.   Thank you much for your work on this.   It has been
a lifesaver on a short time line project assigned to me.

~Jeremy

On Mar 5, 2017 10:51 PM, "Matt Egan" <notifications@github.com> wrote:

Hi There,

Yes the same function used to create a user (duoCreateUser) is used to
modify a user. The difference between creating a user and modifying a user
is that you must provide the user_id to the call when performing an update.

duoCreateUser -user_id DUxxxxxxxxxxxxxxxxx0 -realname "New Name"

Hope that helps
-Matt

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/mbegan/Duo-PSModule/issues/6#issuecomment-284296774>,
or mute the thread

**Comment by mbegan** [comment]
Glad it is helping,

do me a favor if you have time.  Tell your sales rep or CSM about it.

I don't have access to a Duo org anymore (changed jobs) so i cannot test things anymore (their free org doesn't allow the admin api integration).  I reach out to Duo to see if they would hook me up and they came back with a no followed by silence.

I don't think they see value in the project, i think they are being short sighted. If they hear from a few customers they might change their mind and give me access to a full functioning org for testing against.

-Matt

**Comment by jfertig** [comment]
Absolutely will do.   I'll call our rep in the morning and mention this.
Thanks again

~Jeremy

**Comment by jfertig** [comment]
Should have added ... Please let me know if you do not hear anything in the
next month or so.   If not, I will press  harder.    This project has been
very helpful for me and I appreciate the work you have put into this.

Jeremy

**Comment by mbegan** [comment]
Thanks, my ticket # with them is 00152839
